// Read/write src/lib/liquipedia/data.ts — the generated snapshot the app ships.
//
// The file is TypeScript so the app can import it directly with no loader, but
// its four exports are plain JSON literals, which is what lets a plain-JS
// script round-trip them. Both the incremental refresh and the full rebuild go
// through here so there is one definition of the file's shape.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
export const DATA_PATH = resolve(ROOT, "src/lib/liquipedia/data.ts");

/**
 * Parse the generated file. A failed match throws rather than returning an
 * empty dataset — silently "recovering" from an unreadable file would let a
 * merge repopulate it from scratch and quietly drop everything it couldn't
 * re-derive.
 */
export function readDataset(path = DATA_PATH) {
  const src = readFileSync(path, "utf8");
  const block = (name) => {
    const m = src.match(new RegExp(`export const ${name}[^=]*= (\\[[\\s\\S]*?\\]|\\{[\\s\\S]*?\\});\\n`));
    if (!m) throw new Error(`could not locate ${name} in ${path}`);
    return JSON.parse(m[1]);
  };
  return {
    sources: block("SOURCES"),
    majors: block("MAJORS"),
    editions: block("RANKING_EDITIONS"),
    players: block("PLAYERS"),
  };
}

export function writeDataset({ sources, majors, editions, players }, asOf, path = DATA_PATH) {
  const json = (v) => JSON.stringify(v, null, 2);
  writeFileSync(
    path,
    `// Bundled snapshot of Liquipedia's Melee history data. The dashboard is
// zero-backend with a locked-down CSP (self + Supabase only), so this ships
// with the app instead of being fetched at runtime.
//
// Generated by scripts/refresh-liquipedia.mjs (incremental, run weekly) or
// scripts/rebuild-liquipedia.mjs (from scratch) — do not hand-edit. Content
// compiled from Liquipedia (liquipedia.net/smash), licensed CC BY-SA 3.0.

import type { Major, PlayerMeta, RankingEdition, Source } from "./types";

export const DATA_AS_OF = ${JSON.stringify(asOf)};

export const SOURCES: Source[] = ${json(sources)};

export const MAJORS: Major[] = ${json(majors)};

export const RANKING_EDITIONS: RankingEdition[] = ${json(editions)};

export const PLAYERS: Record<string, PlayerMeta> = ${json(players)};
`,
  );
}

export const SOURCES = [
  { label: "Liquipedia — Melee Major Tournaments", url: "https://liquipedia.net/smash/Major_Tournaments/Melee" },
  { label: "Liquipedia — SSBMRank (all editions)", url: "https://liquipedia.net/smash/SSBMRank" },
  { label: "Liquipedia — player pages (career winnings)", url: "https://liquipedia.net/smash/Portal:Players" },
];

export const today = () => new Date().toISOString().slice(0, 10);
